### ISSUE TITLE
Markdown Support

### ISSUE THREAD

**Issue by Bubu** [indication/OpenRedmine#188]
I was trying out this app and I noticed the wiki styling information is completely missing inside the app. Our Redmine is set up for markdown support and this is not interpreted by OpenRedmine.

What's worse, newlines are not rendered as well making the text almost illegible.

Is there supposed to be support for basic wiki styling? How hard would it be to add?
I did a quick search on the code and there are some markdown and textile classes but I didn't look further into it.

**Comment by indication** [comment]
Thank you for testing.
We tried to support markdown style few years ago, but there is major function to support markdown (implemented 2.5 in 2014 as experimental method, ), app supports .
Now, it is time to support. Related #114

**Comment by indication** [comment]
This will be released in #210

**Comment by indication** [comment]
Pre-released as v3.22-rc2_635
