### ISSUE TITLE
Bulid does not have version name nor version code

### ISSUE THREAD

**Issue by mimi89999** [indication/OpenRedmine#222]
Hello. I'm an F-Droid maintainer and I wanted to update OpenRedmine on F-Droid. It is not possible to build the latest version of OpenRedmine as neither the version name nor the version code are defined in the source code. This make building the latest version of OpenRedmine impossible.

**Comment by indication** [comment]
Thank you for reporting issue.
Could you define `TRAVIS_TAG` as version name?
Or please tell me F-Droid build environment variables?

**Comment by mimi89999** [comment]
We can set any environment variable, but we need to know what to set it to. I don't quite understand how the version code is computed. It would be best if the version name and code in F-Droid and in the PlayStore are the same.

**Comment by wavepack3t** [comment]
@mimi89999
It looks like the Play Store version of OpenRedmine is 3.22 while the F-Droid version is 3.21. These numbers coincide with the last two tagged releases on GitHub -- https://github.com/indication/OpenRedmine/releases

I am not familiar with how F-Droid keeps its builds up to date, but surely there are other projects in the metadata repo who rely on GitHub release tag numbers for versioning?

Forgive me if what I said makes no sense, I am fairly new to F-Droid.

Many thanks to you both, @mimi89999 for taking the time to maintain F-Droid and @indication for taking the time to build a FOSS client for Redmine!

**Comment by wavepack3t** [comment]
One more note... I tried downloading OpenRedmine from the Google Play store and it seems to hang in the `Downloading...` state forever. I'll stick with the `3.21` version on F-Droid for now. Please let me know if there's any way I can help with this upgrade!

**Comment by mimi89999** [comment]
I fixed this manually in https://gitlab.com/fdroid/fdroiddata/commit/7669d020 .

**Comment by indication** [comment]
Thank you for support @wavepack3t, @mimi89999 .

I think about build-system to fit travis-ci and f-droid, but there is better solution to auto numbering the commit.
OpenRedmine is very low avtivity, currently. It is better to change build system(manually numbering).
On next release, API version is manually numbering.

**Comment by wavepack3t** [comment]
Thank you Mimi for the manual fix!
I was able to upgrade to the newer release in F-Droid.

The F-Droid bot has since downgraded to 3.21 again https://gitlab.com/fdroid/fdroiddata/commit/1adf065248c904db23687731b4faeaa41a02c370 but your fix allowed the 3.22 version to build, and so it is available as a relatively hidden option for those who know about it.

**Comment by PanderMusubi** [comment]
Please see https://gitlab.com/fdroid/fdroiddata/issues/1806 on how to get automatically latest version build and published on F-Droid.

**Comment by indication** [comment]
Can I tag it as `2.23`?
- Version Name and Version Code is fully manual writing, now.
- Embedded build tag on the config because we should know where the apk is built.
    - On F-Droid, it may use `CI_JOB_NAME`
    - On Play Store(Travis-CI), it uses `TRAVIS_BRANCH` and `TRAVIS_BUILD_NUMBER`

**Comment by indication** [comment]
Now, released 2.23 on  20% of play store users.
Next day, would be all of users.

**Comment by PanderMusubi** [comment]
I have asked in the issue for F-Droid that someone will give you feedback on the version number.

**Comment by licaon-kter** [comment]
2.23 or 3.23?

**Comment by indication** [comment]
Sorry, the version is 3.23.
CI_JOB_NAME is seen on f-droid build scripts.

I found the document from GitLab CI : https://docs.gitlab.com/ee/ci/variables/ .
Is it better to use CI_JOB_ID?

**Comment by licaon-kter** [comment]
So you define them here: https://github.com/indication/OpenRedmine/blob/6227e1a7f1273c6e5bb59d05d968fe9361fa5338/OpenRedmine/build.gradle#L10

Then 12 lines later you use them.... and never again (!?), if so why not define them in one place (in the place as versionName and Code) and we can just use them as expected.

**Comment by indication** [comment]
I was misunderstand that version code is included the source code.
To correct, I must write following. Right?

```
        versionCode 665
        versionName "3.23"
```

**Comment by licaon-kter** [comment]
Yes, that's the one

**Comment by indication** [comment]
Thank you very much for support about build.

How about re-tag (force update) as v3.23?
Dose it work well?
If not, I would be tag as v3.23.1.

**Comment by licaon-kter** [comment]
Retag, yes

**Comment by indication** [comment]
Re-tagged.

**Comment by licaon-kter** [comment]
Thanks, https://gitlab.com/fdroid/fdroiddata/merge_requests/5654

**Comment by indication** [comment]
Thanks a lot.
